<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Herr+Von+Muellerhoff" rel="stylesheet">
<link rel="stylesheet" href="${ctx}/res/css/open-iconic-bootstrap.min.css">
<link rel="stylesheet" href="${ctx}/res/css/animate.css">
<link rel="stylesheet" href="${ctx}/res/css/owl.carousel.min.css">
<link rel="stylesheet" href="${ctx}/res/css/owl.theme.default.min.css">
<link rel="stylesheet" href="${ctx}/res/css/magnific-popup.css">
<link rel="stylesheet" href="${ctx}/res/css/aos.css">
<link rel="stylesheet" href="${ctx}/res/css/ionicons.min.css">
<link rel="stylesheet" href="${ctx}/res/css/bootstrap-datepicker.css">
<link rel="stylesheet" href="${ctx}/res/css/jquery.timepicker.css">
<link rel="stylesheet" href="${ctx}/res/css/flaticon.css">
<link rel="stylesheet" href="${ctx}/res/css/icomoon.css">
<link rel="stylesheet" href="${ctx}/res/css/style.css">
<link rel="stylesheet" href="${ctx}/res/css/flag-icon.min.css">
<link rel="stylesheet" href="${ctx}/res/css/custom.css">